name: socialx
description: "A new Flutter project."

publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

  # UI and icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # Firebase
  cloud_firestore: ^5.6.5
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  flutter_bloc: ^9.0.0
  firebase_storage: ^12.4.4

  # Notifications
  flutter_local_notifications: ^19.0.0

  # files
  cached_network_image: ^3.4.1
  file_picker: ^9.2.0
  flutter_image_compress: ^2.4.0

  # State management
  provider: ^6.0.0

  # Utilities
  timeago: ^3.6.1
  share_plus: ^7.2.1

  # Image picker
  image_picker: ^1.0.7
  image_editor_plus: ^1.0.6

  # Audio recording
  record: ^5.0.4
  permission_handler: ^11.3.0

  # Audio playback
  audioplayers: ^5.2.1

  # Audio visualization
  audio_waveforms: ^1.0.4

  # Path provider
  path_provider: ^2.1.2

  # HTTP
  http: ^1.2.0

  # Extended image
  extended_image: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/social_app_logo.jpg